name: Auto Form Submit

on:
  workflow_dispatch: # GitHubの画面から手動で実行するためのトリガー
  # schedule:
  #   - cron: '0 9 * * *' # 毎日日本時間の18時に自動実行する場合（UTC指定）

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pytest-playwright
          playwright install chromium

      - name: Run automation script
        run: python main.py

